#Service-Two Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceTwo.name }}
  labels:
    app: {{ .Values.serviceTwo.name }}
spec:
  selector:
    app: {{ .Values.serviceTwo.name }}
  ports:
    - name: http-two
      protocol: TCP
      port: {{ .Values.serviceTwo.port }}
      targetPort: {{ .Values.serviceTwo.port }}