#Service-One Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceOne.name }}
  labels:
    app: {{ .Values.serviceOne.name }}
spec:
  selector:
    app: {{ .Values.serviceOne.name }}
  ports:
    - name: http-one
      protocol: TCP
      port: {{ .Values.serviceOne.port }}
      targetPort: {{ .Values.serviceOne.port }}